name: Ubuntu Tests

on:
  push:
    branches:
      - 'master'
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ubuntu_ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checking out
        uses: actions/checkout@v3
        with:
          fetch-tags: True
          fetch-depth: 0
      - run: git tag -l
      - run: git describe --tags
      - name: Building image
        run: docker build -t hhvm-test -f ci/Dockerfile .
      - name: Running tests
        run: docker run -v .:/source -w /source hhvm-test:latest ci/run_tests.sh
